### ISSUE TITLE
[FEATURE REQ] Node connection lines don't update when a node is collapsed.

### ISSUE THREAD

**Issue by gamaraala666** [niknah/quick-connections#10]
This is a feature request more than a bug. 
There are some nodes, specially in saved templates that are just utility nodes which are pretty much always kept collapsed to optimize space and graph clarity. But unfortunately the 'circuit board' line type refuses to update when node is collapsed and **uses the full size** of the node **all the time**. 

It would be awesome if it properly reacted when a node is collapsed. 

Lastly, let me just say i love this work and it's in my personal list must have extensions already. ❤️

**Comment by niknah** [comment]
Thanks for telling me about it.  I have updated it so it uses the correct size of collapsed nodes.

**Comment by gamaraala666** [comment]
you are awesome! <3
