### ISSUE TITLE
Add setting option "Do not apply to AnyType"

### ISSUE THREAD

**Issue by mijuku233** [niknah/quick-connections#13]
Thank you very much for your node, it's great, but there is a problem that affects the experience.
When there are `AnyType` inputs or outputs in the workflow, they will interfere with our selection. It would be better to add an option to disable the operation on `AnyType`.

![image](https://github.com/user-attachments/assets/c138f59a-5ba0-4e47-89a9-7c4848653afe)

**Comment by niknah** [comment]
Thanks for this.  I have updated it, and made the area clearer to read.

**Comment by mijuku233** [comment]
> Thanks for this. I have updated it, and made the area clearer to read.

After the update, connecting `*` type input and output will cause comfyui to freeze

**Comment by niknah** [comment]
I've made a fix that causes it to freeze when there are no connections to show.  Maybe this was the issue.  Tell me if it works.

**Comment by mijuku233** [comment]
> I've made a fix that causes it to freeze when there are no connections to show. Maybe this was the issue. Tell me if it works.

Thank you, after testing, dragging the `*` type input and output no longer causes comfyui to freeze.
But there are still some minor issues
1. Dragging the `*` input will still react to all outputs

2. The `Quick Connect` triggered by the input is too sensitive, and it will even perform a `Quick Connect` when I just click the input point

![cc](https://github.com/user-attachments/assets/c8bf2f45-b206-40d0-ac16-18c1d62bf484)

**Comment by niknah** [comment]
Thanks.  I have updated it so it shows nothing on nodes that can be connected to anything.

**Comment by mijuku233** [comment]
> Thanks. I have updated it so it shows nothing on input/outputs that can be connected to anything.

great!
