### ISSUE TITLE
[Request] Separate Quick Connections and Circuit Board Lines extensions

### ISSUE THREAD

**Issue by LukeG89** [niknah/quick-connections#16]
Would it be possible to separate the two extensions?

I would like to completely disable Circuit Board Lines from the extension panel, since I don't use them.

Currently there is only one option that disables everything.

![extension](https://github.com/user-attachments/assets/e1823f27-80d8-42fe-842b-19f3646bd34f)

**Comment by niknah** [comment]
Thanks.  I didn't know about this extension feature in the options.

**Comment by LukeG89** [comment]
Thanks to you! 😄 

> I didn't know about this extension feature in the options.

Yeah, it's a beta feature you have to enable in the Settings

![extension](https://github.com/user-attachments/assets/f4ec78d8-d3d1-4d12-86a3-a0ea00132374)
