### ISSUE TITLE
Import Failed Error

### ISSUE THREAD

**Issue by camoody1** [niknah/quick-connections#4]
At Comfy start, I get this error...
0.0 seconds (IMPORT FAILED): H:\ComfyUI v2\ComfyUI_windows_portable\ComfyUI\custom_nodes\quick-connections

I see no other errors in my startup log. There's nothing that gives me any indication of why it's failing to import.

Thoughts?

**Comment by niknah** [comment]
Not sure.  It was missing NODE_CLASS_MAPPINGS, I have added that now.  Update to see if it helps.
They made some big changes the UI recently.

**Comment by niknah** [comment]
I think this is fixed in https://github.com/niknah/quick-connections/issues/11
Send me a workflow if you have problems.
