### ISSUE TITLE
原本spline的连线怎么变回来

### ISSUE THREAD

**Issue by xueqing0622** [niknah/quick-connections#5]
现在这个连线也不错，不过还是有人习惯spline，是否给个选择可以用回spline的

**Comment by niknah** [comment]
转至选项和快速连接 > “关闭”

**Comment by xueqing0622** [comment]
关闭后只是不能快速连接，线段还是变不回去。
是要刷新还是什么操作

**Comment by niknah** [comment]
抱歉，我不明白。它应该这样工作...

![t](https://github.com/user-attachments/assets/9c2bc986-7288-403a-8bdb-cd138ad83ddd)

**Comment by xueqing0622** [comment]
没事 也挺好
习惯你这个新的线段也挺好
