### ISSUE TITLE
Selected node doesn't have white connections

### ISSUE THREAD

**Issue by zymox** [niknah/quick-connections#7]
In the default behaviour, when you have a node selected, all input/output connections are displayed in white for easier following. 
With the circuit board enabled, that's not happening anymore. I think it would be worthwhile to keep that feature.

**Comment by niknah** [comment]
Is there another custom node or an option that I have to tick to get the white input/output?   When I click on a node, I see a white outline on the node but the connections stay the same.

**Comment by lldacing** [comment]
> Is there another custom node or an option that I have to tick to get the white input/output? When I click on a node, I see a white outline on the node but the connections stay the same.

我遇到了同样的问题，不是其它自定义插件引起的，因为我安装之前是好的，另外能不能为电路板线加个开关。
I encountered the same problem. It was not caused by other custom nodes because it was fine before I installed it. Also, can you add a switch for the circuit board line?

**Comment by lldacing** [comment]
> > Is there another custom node or an option that I have to tick to get the white input/output? When I click on a node, I see a white outline on the node but the connections stay the same.
> 
> 我遇到了同样的问题，不是其它自定义插件引起的，因为我安装之前是好的，另外能不能为电路板线加个开关。 I encountered the same problem. It was not caused by other custom nodes because it was fine before I installed it. Also, can you add a switch for the circuit board line?

我找到电路板线的开关了。另外，这个问题在选择电路板线时发生
I found the switch for the circuit board line. Also, this problem occurs when selecting the circuit board line

**Comment by niknah** [comment]
Thanks for telling me about this.  I have fixed it in the latest update.
