### ISSUE TITLE
[FEATURE] Allow for less strict mouse positionning

### ISSUE THREAD

**Issue by brayevalerien** [niknah/quick-connections#9]
# Description of the Issue
The quick connection feature is very handy and it is the closest thing to Blender node wrangler we have for ComfyUI.

However after a bit of use, I find that a lot of times I miss the spot when I try to connect quickly to another node because the dot that the connection needs to be connected too is pretty small. This does not allow for quick drag connexion like the Alt+drag feature of Blender node wrangler, makes things a bit slower and more frustrating

# Proposed solution
Inspired by the Alt+drag feature of node wrangler, I suggest the following, or something similar:
When you want to use quick connections, you hold the Alt key, click on the node socket and drag outside of the node. If there is a single option for where the connection can go, releasing anywhere will connect to that option. If there are multiple option, the space next to the node is divided in as many sections (for instance if the socket can be connected to 3 other sockets, the space where you are dragging too is devided in 3 equal parts), and releasing in one of these section with connect to the corresponding option.

Quick mockup of what it could look like when there are 3 options:
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/0e0541ee-0bd4-463d-a741-f2fa01697c85">

And if Alt is not held when clicking on a socket, the behaviour is following ComfyUI behaviour. This has the benefit of not displaying random infos when you don't want to use quick connexions, without needing to disable it.

**Comment by niknah** [comment]
Thanks for this.  I can't place things above the output / input connections because when you put your mouse over it for a second, ComfyUI will put a tooltip over that area and hide the quick connections.  Instead, I have made it so when you zoom out the quick connections stay the same size.

**Comment by brayevalerien** [comment]
I see. There are probably other possible solutions to this issue. The current problem for me is that it's impractical to have to be precise with my mouse when all I want is go faster.

**Comment by niknah** [comment]
I have added an option in settings under quick-connections, "connect with dot". When it is disabled, it will connect with the text as well.
I tried this out and was annoying when I was creating nodes up close, the text would block out nodes that were close by.  So it is connecting with the dot only by default.

**Comment by brayevalerien** [comment]
Ah this could be a bit better, thank you.
